format:
	gofmt -w *.go

day01build:
	mkdir -p build
	go build -o build/day-01 day-01.go
	chmod +x build/day-01

day01run:
	./build/day-01 day-01-input.txt

day02build:
	mkdir -p build
	go build -o build/day-02 day-02.go
	chmod +x build/day-02

day02run:
	./build/day-02 day-02-input.txt

day03build:
	mkdir -p build
	go build -o build/day-03 day-03.go
	chmod +x build/day-03

day03run:
	./build/day-03 day-03-input.txt

day04build:
	mkdir -p build
	go build -o build/day-04 day-04.go
	chmod +x build/day-04

day04run:
	./build/day-04 day-04-input.txt

day05build:
	mkdir -p build
	go build -o build/day-05 day-05.go
	chmod +x build/day-05

day05run:
	./build/day-05 day-05-input.txt

day06build:
	mkdir -p build
	go build -o build/day-06 day-06.go
	chmod +x build/day-06

day06run:
	./build/day-06 day-06-input.txt

b7:
	mkdir -p build
	go build -o build/7 7.go
	chmod +x build/7

r7:
	./build/7 7input.txt

