format:
	gofmt -w *.go


build22:
	mkdir -p build
	go build -o build/02-2 02-2.go
	chmod +x build/02-2

run22:
	./build/02-2 02-input.txt

build31:
	mkdir -p build
	go build -o build/03-1 03-1.go
	chmod +x build/03-1

run31:
	./build/03-1 03-input.txt

build32:
	mkdir -p build
	go build -o build/03-2 03-2.go
	chmod +x build/03-2

run32:
	./build/03-2 03-input.txt
